### ISSUE TITLE
Call to a member function queryEntries() on null

### ISSUE THREAD

**Issue by mvpopuk** [mitydigital/statamic-feedamic#6]
Hi there. First of all thanks for this package. It is great.

It all worked great until I got a `500 Server Error` for `/feed` or `feed/atom`

This is the error: 

`
Call to a member function queryEntries() on null
`

```php
return Collection::findByHandle($handle)

               ->queryEntries() // <-- this line throws the error because is getting null

                ->orderBy('updated_at', 'desc')

                ->get()

                ->filter(function (\Statamic\Entries\Entry $entry) {

                    // is the entry published?

                    if (!$entry->published()) {

                        return false;

                    }
```

Error log:

```
[2022-07-17 10:48:25] local.ERROR: Call to a member function queryEntries() on null {"userId":"eded133e-fee3-457f-838f-e388d73b3c39","exception":"[object] (Error(code: 0): Call to a member function queryEntries() on null at /Users/mvpsoft/Code/laravelmagazine/vendor/mitydigital/feedamic/src/Http/Controllers/FeedamicController.php:79)
[stacktrace]
#0 [internal function]: MityDigital\\Feedamic\\Http\\Controllers\\FeedamicController->MityDigital\\Feedamic\\Http\\Controllers\\{closure}('news', 1)
#1 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(695): array_map(Object(Closure), Array, Array)
#2 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(354): Illuminate\\Support\\Collection->map(Object(Closure))
#3 /Users/mvpsoft/Code/laravelmagazine/vendor/mitydigital/feedamic/src/Http/Controllers/FeedamicController.php(193): Illuminate\\Support\\Collection->flatMap(Object(Closure))
#4 /Users/mvpsoft/Code/laravelmagazine/vendor/mitydigital/feedamic/src/Http/Controllers/FeedamicController.php(23): MityDigital\\Feedamic\\Http\\Controllers\\FeedamicController->loadFeedEntries()
#5 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(426): MityDigital\\Feedamic\\Http\\Controllers\\FeedamicController->MityDigital\\Feedamic\\Http\\Controllers\\{closure}()
#6 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(418): Illuminate\\Cache\\Repository->rememberForever('feedamic', Object(Closure))
#7 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Cache\\CacheManager->__call('rememberForever', Array)
#8 /Users/mvpsoft/Code/laravelmagazine/vendor/mitydigital/feedamic/src/Http/Controllers/FeedamicController.php(24): Illuminate\\Support\\Facades\\Facade::__callStatic('rememberForever', Array)
#9 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(426): MityDigital\\Feedamic\\Http\\Controllers\\FeedamicController->MityDigital\\Feedamic\\Http\\Controllers\\{closure}()
#10 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(418): Illuminate\\Cache\\Repository->rememberForever('feedamic.rss', Object(Closure))
#11 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Illuminate\\Cache\\CacheManager->__call('rememberForever', Array)
#12 /Users/mvpsoft/Code/laravelmagazine/vendor/mitydigital/feedamic/src/Http/Controllers/FeedamicController.php(28): Illuminate\\Support\\Facades\\Facade::__callStatic('rememberForever', Array)
#13 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): MityDigital\\Feedamic\\Http\\Controllers\\FeedamicController->rss()
#14 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('rss', Array)
#15 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Routing/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(MityDigital\\Feedamic\\Http\\Controllers\\FeedamicController), 'rss')
#16 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#17 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate\\Routing\\Route->run()
#18 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#27 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#34 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#35 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#36 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#37 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#38 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Users/mvpsoft/Code/laravelmagazine/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\DisableFloc->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /Users/mvpsoft/Code/laravelmagazine/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /Users/mvpsoft/Code/laravelmagazine/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /Users/mvpsoft/Code/laravelmagazine/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /Users/mvpsoft/Code/laravelmagazine/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /Users/mvpsoft/Code/laravelmagazine/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /Users/mvpsoft/Code/laravelmagazine/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#63 /Users/mvpsoft/Code/laravelmagazine/vendor/torchlight/torchlight-laravel/src/Middleware/RenderTorchlight.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#64 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Torchlight\\Middleware\\RenderTorchlight->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#67 /Users/mvpsoft/Code/laravelmagazine/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#68 /Users/mvpsoft/Code/laravelmagazine/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#69 /Users/mvpsoft/.composer/vendor/laravel/valet/server.php(234): require('/Users/mvpsoft/...')
#70 {main}
"} 

```

In `feedamic.php` for the `collections` key I have the following:

```php
 'collections' => [
        'blog',
        'news',
        'podcast',
        'links'
    ],
```

so this should never return `null`

Looking forward for your thoughts.
Thanks in advance for your time.

**Comment by martyf** [comment]
I’m out of the office a bit this week so may be slow to reply, sorry. 

What version of Statamic are you using?

And your `$collections` array contains the correct handles for your collections? 

If you remove them one by one, can you identify which one is causing the issue? ie just do ‘blog’ then just do ‘news’ etc.

**Comment by martyf** [comment]
Closing, due to no reply
